// apps/demo-vue/app/plugin-demos/rich-text-editor.vue
<template>
  <Page>
    <ActionBar title="rich-text-editor" class="action-bar">
      <ActionItem ios.systemIcon="2" ios.position="right" android.position="actionBar" @tap="openTools" android:text="Link"></ActionItem>
    </ActionBar>

    <GridLayout class="p-20" rows="*">
      <RichEditor :data="data" @textChange="textChange" @loaded="loadedEditor" />
    </GridLayout>
  </Page>
</template>

<script>
import Vue from 'nativescript-vue';
import { DemoSharedRichTextEditor } from '@demo/shared';
const demoShared = new DemoSharedRichTextEditor();

export default {
  mounted() {
    demoShared.on('propertyChange', () => {
      // reacting to {N} observable to update Vue2 reactive binding
      this.data = demoShared.data;
    });
  },
  data() {
    return {
      data: demoShared.data,
      openTools: demoShared.openTools.bind(demoShared),
      textChange: demoShared.textChange.bind(demoShared),
      loadedEditor: demoShared.loadedEditor.bind(demoShared),
    };
  },
};
</script>

// apps/demo-angular/src/plugin-demos/rich-text-editor.component.ts
import { Component, NgZone } from '@angular/core';
import { DemoSharedRichTextEditor } from '@demo/shared';
import { RichEditor } from '@marblsy/rich-text-editor';
import { registerElement } from '@nativescript/angular';
registerElement('RichEditor', () => RichEditor);

@Component({
  selector: 'demo-rich-text-editor',
  templateUrl: 'rich-text-editor.component.html',
})
export class RichTextEditorComponent {
  demoShared: DemoSharedRichTextEditor;

  constructor(private _ngZone: NgZone) {}

  ngOnInit() {
    this.demoShared = new DemoSharedRichTextEditor();
  }
}

<ActionBar title="rich-text-editor" class="action-bar">
  <ActionItem ios.systemIcon="2" ios.position="right" android.position="actionBar" (tap)="demoShared.openTools()" android:text="Link"></ActionItem>
</ActionBar>

<GridLayout class="p-20" rows="*">
  <RichEditor [data]="demoShared.data" (textChange)="demoShared.textChange($event)" (loaded)="demoShared.loadedEditor($event)" />
</GridLayout>
